[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "rust_tokenizer"
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "maturin>=1.9.3",
]

[tool.maturin]
features = ["pyo3/extension-module"]
